### ISSUE TITLE
help

### ISSUE THREAD

**Issue by hongzhangMu** [twtygqyy/resnet-cifar10#1]
hi:
I want to study faster-rcnn using resnet in matlab. I can't run it. can you tell me how to run it ?

**Comment by twtygqyy** [comment]
@hongzhangMu I'm sorry I haven't run faster-rcnn + resnet on Matlab, but you can check my previous issue in py-faster-rcnn repo here #https://github.com/rbgirshick/py-faster-rcnn/issues/62
