### ISSUE TITLE
code for data augmentation

### ISSUE THREAD

**Issue by hshustc** [twtygqyy/resnet-cifar10#2]
Hi. I can't reproduce the reported result using the provided prototxt. So would you please make the code for data augmentation available too? Thanks a lot.

**Comment by twtygqyy** [comment]
@hshustc  Thanks for your interests, I will push the code soon.

**Comment by twtygqyy** [comment]
Please find the code for data augmentation here https://github.com/twtygqyy/caffe-augmentation
