### ISSUE TITLE
can you share your data?

### ISSUE THREAD

**Issue by fastalgo** [twtygqyy/resnet-cifar10#3]
Sorry, I can't reproduce your results.

Can you share your train and test data?

Thanks!

**Comment by twtygqyy** [comment]
@fastalgo please find the modified training images with zero padding here [https://drive.google.com/file/d/0B5i4atpKg9EcZWRCOVFEUHJkSWM/view](url)

**Comment by fastalgo** [comment]
Sorry, this link is broken. Can you share another?

**Comment by twtygqyy** [comment]
@fastalgo I just updated the README, you can use the link I provided.

**Comment by fastalgo** [comment]
Thanks!
