### ISSUE TITLE
test initialization

### ISSUE THREAD

**Issue by huangh12** [twtygqyy/resnet-cifar10#5]
Hello, 
   Thank you very much for your code.
   I've noticed that you set "test initialization: true" in [your solver.proto](https://github.com/twtygqyy/resnet-cifar10/blob/master/resnet20/solver.prototxt#L12). But I also found [somebody](https://github.com/beniz/deepdetect/blob/master/templates/caffe/resnet_50/resnet_50_solver.prototxt#L4) set it to false. Can you explain the effect of this parameter settting. Thank you again :)

**Comment by twtygqyy** [comment]
@huangh12 "test initialization: true" means that the training will start with evaluating the precision on validation set, using randomly generated weights according to you initialization method.

**Comment by huangh12** [comment]
Oh, great! Thank you.
